version: '3.5'

services:
    etcd0:
        image: quay.io/coreos/etcd:v3.5.3
        container_name: etcd0
        entrypoint: /usr/local/bin/etcd
        command:
            - '--name=etcd0'
            - '--initial-advertise-peer-urls=http://etcd0:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd0:2379'
            - '--initial-cluster-token=etcd-cluster-0'
            - '--initial-cluster=etcd0=http://etcd0:2380'
            - '--initial-cluster-state=new'
            - '--max-request-bytes=10485760'

    clickhouse:
        image: yandex/clickhouse-server
        container_name: clickhouse
        volumes:
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    grafana:
        image: grafana/grafana:6.7.2
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
        volumes:
            - ./grafana-storage:/var/lib/grafana
        ports:
            - 3000:3000

    machine_node_1:
        build:
            context: ../../
            dockerfile: ./machine_node/Dockerfile
        container_name: machine_node_1
        entrypoint: /gostreaming/bin/machine_node
        command:
            - '--config=/gostreaming/config/machine_node_config.yaml'
        volumes:
            - ./config:/gostreaming/config:ro
        depends_on:
            - etcd0
            - clickhouse

    machine_node_2:
        build:
            context: ../../
            dockerfile: ./machine_node/Dockerfile
        container_name: machine_node_2
        entrypoint: /gostreaming/bin/machine_node
        command:
            - '--config=/gostreaming/config/machine_node_config.yaml'
        volumes:
            - ./config:/gostreaming/config:ro
        depends_on:
            - etcd0
            - clickhouse

    machine_node_3:
        build:
            context: ../../
            dockerfile: ./machine_node/Dockerfile
        container_name: machine_node_3
        entrypoint: /gostreaming/bin/machine_node
        command:
            - '--config=/gostreaming/config/machine_node_config.yaml'
        volumes:
            - ./config:/gostreaming/config:ro
        depends_on:
            - etcd0
            - clickhouse

    meta_node:
        build:
            context: ../../
            dockerfile: ./meta_node/Dockerfile
        container_name: meta_node
        entrypoint: /gostreaming/bin/meta_node
        ports:
            - 5555:5555
        command:
            - '--config=/gostreaming/config/meta_node_config.yaml'
        volumes:
            - ./config:/gostreaming/config:ro
        depends_on:
            - machine_node_1
            - machine_node_2
            - machine_node_3
