http:
  host: 0.0.0.0
  port: 8181

logging:
  logfile: /var/log/machine_node/machine_node.log
  level: info

etcd:
  endpoints: ['127.0.0.1:2379']
  timeout: 1m
  retry:
    delay: 1s
    count: 10

watcher:
  pings-to-stop: 3
  ping-freq: 3s

action-start-retry:
  delay: 1s
  count: 10

runtime-path: /gostreaming/bin/runtime
runtime-logs-dir: /var/log/runtime
